version: '3.8'

services:
  db:
    image: postgres
    container_name: fdn-postgres
    environment:
      POSTGRES_USER: fdn
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fdn-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
